services:
  jenkins:
    build:
      context: ./jenkins
    container_name: aml-jenkins
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./:/workspace/aml-monitoring-pipeline
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: aml-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: aml-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: aml-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://aml-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    container_name: aml-postgres
    environment:
      POSTGRES_USER: amluser
      POSTGRES_PASSWORD: amlpass
      POSTGRES_DB: amldb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  jobmanager:
    build:
      context: ./flink
    container_name: aml-flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 16
        parallelism.default: 16
      - KAFKA_BOOTSTRAP_SERVERS=aml-kafka:29092
      - KAFKA_INPUT_TOPIC=txn.raw
      - KAFKA_ALERT_TOPIC=aml.alerts
      - AML_FLINK_GROUP_ID=aml-pattern-detector-flink-v1
      - PYFLINK_CLIENT_EXECUTABLE=/usr/bin/python3
      - PYFLINK_PYTHON=/usr/bin/python3
    volumes:
      - ./:/opt/aml
    depends_on:
      - kafka

  taskmanager:
    build:
      context: ./flink
    container_name: aml-flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 16
        parallelism.default: 16
      - KAFKA_BOOTSTRAP_SERVERS=aml-kafka:29092
      - KAFKA_INPUT_TOPIC=txn.raw
      - KAFKA_ALERT_TOPIC=aml.alerts
      - AML_FLINK_GROUP_ID=aml-pattern-detector-flink-v1
      - PYFLINK_CLIENT_EXECUTABLE=/usr/bin/python3
      - PYFLINK_PYTHON=/usr/bin/python3
    volumes:
      - ./:/opt/aml

  airflow-postgres:
    image: postgres:15
    container_name: aml-airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: aml-airflow-init
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --password admin --firstname AML --lastname Admin --role Admin --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: aml-airflow-webserver
    depends_on:
      - airflow-init
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AML_POSTGRES_HOST: postgres
      AML_POSTGRES_PORT: 5432
      AML_POSTGRES_DB: amldb
      AML_POSTGRES_USER: amluser
      AML_POSTGRES_PASSWORD: amlpass
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: aml-airflow-scheduler
    depends_on:
      - airflow-webserver
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AML_POSTGRES_HOST: postgres
      AML_POSTGRES_PORT: 5432
      AML_POSTGRES_DB: amldb
      AML_POSTGRES_USER: amluser
      AML_POSTGRES_PASSWORD: amlpass
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: scheduler

volumes:
  jenkins_home:
